function permuteAPalindrome(input) {
  let map = {}, count = 0;
  for (let i = 0; i < input.length; i++) {
    const e = input.charAt(i);
    if (map[e]) map[e]++;
    else map[e] = 1;
  }
  for (const key in map) {
    const frc = map[key];
    if (frc % 2 == 1) count++;
  }
  return count < 2;
}

// console.log(permuteAPalindrome("racecars")); //false
console.time("T")
console.log(permuteAPalindrome("phhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqspphhpucpjyecwpyyykjvesbopffjjpsblwljcuekqeqnsolvlcnqjpqsp")); //true
console.timeEnd("T") // ~ 8ms
